# Generated by Django 6.1.1 on 2026-10-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Vehical_NO', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Vehical_Name', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
